version: '3'

services:
  listo:
    image: listo
    build:
      context: .
      args:
        REACT_APP_TRELLO_JIRA_MODE: $REACT_APP_TRELLO_JIRA_MODE
    environment:
      - DATA_DIR=/etc/listo/data
      - DISK_PATH=/opt/listo/db.json
      - REACT_APP_API_URL
      - TRELLO_JIRA_MODE
      - REACT_APP_TRELLO_JIRA_MODE
      - TRELLO_API_KEY
      - TRELLO_TOKEN
      - TRELLO_TEAM
      - TRELLO_BOARD_LINK
      - JIRA_HOST
      - JIRA_USER
      - JIRA_PASSWORD
      - JIRA_PROJECT
      - JIRA_TASK_ID
      - JIRA_SUBTASK_ID
      - JIRA_PROJECT_ID
      - JIRA_ASSIGN_OR_COMPONENT
      - SLACK_CHANNEL_LINK
      - SLACK_TARGET_CHANNEL
      - SLACK_WEB_HOOK

    volumes:
        - ../infosec-listo/data:/etc/listo/data:ro
    ports:
      - 8000:8000