version: '3'

services:
  listo:
    image: listo
    build: .
    environment:
      - DATA_DIR=/etc/listo/data
      - DISK_PATH=/opt/listo/db.json
      - TRELLO_JIRA_MODE
      - TRELLO_API_KEY
      - TRELLO_TOKEN
      - TRELLO_TEAM
      - TRELLO_BOARD_LINK
      - SLACK_CHANNEL_LINK
      - SLACK_TARGET_CHANNEL
      - SLACK_WEB_HOOK
    volumes:
        - ./data:/etc/listo/data:ro
    ports:
      - 8000:8000